- name: Setup backend
  hosts: localhost
  connection: local
  become: yes

  vars:
    db_host: db.daws.info
    db_user: admin
    db_password: ExpenseApp@1
    db_name: expense
    app_location: /app

  roles:
    - common
    - backend
    - db
