- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: download backend code
  ansible.builtin.git:
    repo: "https://github.com/Mani19909/expense-backend.git"
    dest: "{{ app_location }}"

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: install npm dependencies
  ansible.builtin.command: npm install
  args:
    chdir: "{{ app_location }}"

- name: create systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/backend.service
    content: |
      [Unit]
      Description=Backend Service

      [Service]
      User=ec2-user
      WorkingDirectory={{ app_location }}
      ExecStart=/usr/bin/node index.js
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: reload systemd
  ansible.builtin.command: systemctl daemon-reexec

- name: start backend
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes
