- name: wait for DB to be ready
  ansible.builtin.wait_for:
    host: "{{ db_host }}"
    port: 3306
    timeout: 300

- name: check DB connection
  community.mysql.mysql_info:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
  register: db_status

- name: print DB status
  ansible.builtin.debug:
    var: db_status

- name: create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"

- name: create DB user
  community.mysql.mysql_user:
    name: expense
    password: ExpenseApp@1
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
